### ISSUE TITLE
Consistent error handling

### ISSUE THREAD

**Issue by lxmota** [NimbleSM/NimbleSM#184]
Define a standard way to deal with fatal errors within the code. Sometimes they are handled through exceptions, or printing a message to std::err and exiting, but there is no uniform way to deal with this.

**Comment by nmm0** [comment]
Sometimes the behavior is inconsistent whether or not Kokkos is enabled, so that's extra weird.

I guess the first question to ask is if anyone has any particular objection to exceptions from a performance standpoint? Stack unwinding typically has a performance penalty but that will only happen when an exception is thrown, which should only be on an error

**Comment by lxmota** [comment]
My only objection to use exceptions is that exception classes take as an argument to their constructor a std::string & or a char * for the error message, so that it becomes cumbersome to provide more information (say numeric values), as we do here:

https://github.com/NimbleSM/NimbleSM/blob/develop-refactor/src/nimble_mpi.cc#L468

Perhaps there should be error handling functions or macros like we do for Albany here:

https://github.com/SNLComputation/LCM/blob/master/src/Albany_Macros.hpp
