### ISSUE TITLE
NimbleSM Serial won't handle certain exodus files

### ISSUE THREAD

**Issue by jilpi** [NimbleSM/NimbleSM#19]
Running NimbleSM_Serial, files provided with NimbleSM can't be processed or produce unexpected ("non-gold") outputs.

**Mismatch between output and gold file:**
NimbleSM/test/notched_plate/notched_plate_native_neohookean.in
The generated exodus file can be opened with Paraview and is undistinguishable from the gold file by the number of nodes, 3D model, etc. But file sizes are different, and exodiff finds differences between both. See attached exodiff output [exodiff.zip](https://github.com/NimbleSM/NimbleSM/files/4794645/exodiff.zip)

NimbleSM/test/single_elem/single_elem_complex_displacement.in
NimbleSM/test/single_elem/single_elem_native_neohookean.in
(didn't run exodiff but file sizes are different)

**Error in Parser::ReadFile(), unexpected value for "contact visualisation" [...] Core dump**
test/bvh_two_body/two_body_contact.in

**Error in Block::InstantiateMaterialModel(), invalid material model name. Core dump:**
test/notched_plate/notched_plate_lame_hypoelastic.in

**Error in Parser::ReadFile(), unknown key uq model**
test/uq_notch/uq_notch.in

@nmm0 @rjones-sandia

**Comment by nmm0** [comment]
The contact visualization error is due to the visualization code being changed at some point but the benchmark not being updated. That line in the two_body_contact.in file can be removed for now

**Comment by japlews** [comment]
The notched_plate_lame_hypoelastic.in is now part of a separate project which depends on NimbleSM. It should not run unless ‘EXTRAS’ is enabled, and even then, it’s only currently left in for posterity at the point.

On Jun 17, 2020, at 2:09 PM, Nicolas Morales <notifications@github.com<mailto:notifications@github.com>> wrote:



The contact visualization error is due to the visualization code being changed at some point but the benchmark not being updated. That line in the two_body_contact.in file can be removed for now

**Comment by ppebay** [comment]
Checking on status of this issue, should we consider it resolved as it is only optional (`EXTRAS` enabled)?

**Comment by japlews** [comment]
test/notched_plate/notched_plate_lame_hypoelastic.in

Is the only test listed above that requires Nimble extras. It has been moved/copied out into another repo. As for the other material tests (single_elem, notched_plate_native_neohookean...), I think they are real failures.

**Comment by rjones-sandia** [comment]
I think this was an old issue that was resolved when JL (and everyone else) used the diff file instead of the default tolerances for exodiff. 
exodiff -f stem.exodiff current.exo reference.exo
instead of 
exodiff current.exo reference.exo

if the tests are run via make
make -j 40 test
(which I suggest)

the tests we have seen pass previously run fine with "master"
...
      Start 17: brick_with_fibers_mpi_np2
17/19 Test #17: brick_with_fibers_mpi_np2 ..................   Passed    3.93 sec
      Start 18: brick_with_fiber_periodic_serial
18/19 Test #18: brick_with_fiber_periodic_serial ...........   Passed    3.94 sec
      Start 19: quasistatic_tension_serial
19/19 Test #19: quasistatic_tension_serial .................   Passed    1.06 sec

100% tests passed, 0 tests failed out of 19

Total Test time (real) =  73.04 sec

I'm going to close this.
